baseURL = "http://wyyl1.com/"
title = "万有引力一"

# 生成网页保存目录
publishDir = "docs-wyyl1.com"

[params]
  version = "4.x"           # Used to give a friendly message when you have an incompatible update
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2021"            # Site creation time          # 站点建立时间
  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  # 指定 git 仓库地址，可以生成指向最近更新的 git commit 的链接，需要将 enableGitInfo 设置成 true.
  gitRepo = ""

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "万有引力一"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["wyyl1","万有引力一","Hugo"]
  description = "wyyl1 学习笔记"

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = ["baidu_tongji.js"]